### ISSUE TITLE
Release of 0.4.1?

### ISSUE THREAD

**Issue by thickey** [ckirkendall/kioo#50]
Hi Creighton,

Is there any chance of getting a non-snapshot release of the changes that are currently pending for 0.4.1? There have been a number of useful changes since 0.4.0, and it would be really great to have a dependency that isn't a moving target.

Thanks for your time,
Tom Hickey

**Comment by JulianLeviston** [comment]
Is this project still active? I'm also keen to get a working version of Kioo for Reagent 0.5.0

**Comment by aredington** [comment]
I'd like to second this, the latest 0.4.1-SNAPSHOT release has now introduced compilation errors for advance mode due to taking a dependency on cljsjs/react 0.12.2-5.

The last stable release was made over a year ago, that's a significant amount of work to not make available as a stable resource.

**Comment by danlentz** [comment]
I'd also love to see a stable release.  Tracking SNAPSHOT has been problematic for me.

**Comment by ckirkendall** [comment]
The plan is to cut one this weekend.  I know the recent snapshot release caused some issue because we moved to cljsjs/react.

**Comment by aredington** [comment]
Hi @ckirkendall , still hurting for a stable release that is newer than April 23, 2014.

It's okay if it's imperfect as long as it's usable.

**Comment by GetContented** [comment]
@aredington what errors are you seeing when you try snapshot?

**Comment by aredington** [comment]
@GetContented With the latest snapshot (kioo-0.4.1-20150829.145443-10) I haven't experienced any errors compared to the one retrieved in June.

Earlier on June 19 I did experience failures when an 0.4.1 snapshot release broke prior compatibility. Instead of waiting for a breaking snapshot, I'd like to encourage the release of a stable 0.4.1 version that includes the relevant work since April 23, 2014 but does not expose my work to future incompatible changes.

**Comment by ckirkendall** [comment]
Release is out of clojars

**Comment by aredington** [comment]
Thanks, @ckirkendall !
